version: '3.5'

services:
  delta:
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    ports:
      - "8000:80"
    environment:
      ENVIRONMENT: 'development'
      REDIS_URI: 'redis://redis:6379/1'
      DATABASE_URI: 'postgres://postgres:postgres@postgresql:5432/test_rethink_note'

      ALI_ACCESSKEY:
      ALI_SECRET:
      ALI_BUCKET:
      ALI_REGION:
      DEBUG: 'True'
      INTERVAL_SECS:
    entrypoint: /app/docker/entrypoint.sh
    volumes:
      - .:/app
      - /app/src/node_modules
    command: []
    tty: true
    networks:
      - rethink_network


networks:
  rethink_network:
    name: rethink_network_name

